name: CI/CD

on:
  push:
    branches:
      - main  # O el nombre de tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # o la versión que estés utilizando

      - name: Install dependencies
        run: npm install

      - name: Run application
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Tu token de bot
        run: node server.js
