name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Cambia esto según la versión que estés usando

      - name: Install dependencies
        run: npm install

      - name: Run your app
        env:
          BOT_TOKEN: ${{ secrets.MY_BOT_TOKEN }}
          GITHUB_USER: ${{ secrets.MY_GITHUB_USER }}
          GITHUB_REPO: ${{ secrets.MY_GITHUB_REPO }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: npm start
